import { pgTable, text, serial, integer, boolean, timestamp, numeric, jsonb } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { users } from "./models/auth";

// Export all auth models (users and sessions)
export * from "./models/auth";

// === PRODUCTS ===
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
});

export const products = pgTable("products", {
  id: serial("id").primaryKey(),
  sku: text("sku").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  categoryId: integer("category_id").references(() => categories.id),
  price: numeric("price", { precision: 10, scale: 2 }).notNull(),
  costPrice: numeric("cost_price", { precision: 10, scale: 2 }),
  stockQuantity: integer("stock_quantity").notNull().default(0),
  minStockLevel: integer("min_stock_level").default(5),
  imageUrl: text("image_url"),
  isActive: boolean("is_active").default(true),
});

// === CLIENTS ===
export const clients = pgTable("clients", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email"),
  phone: text("phone"),
  address: text("address"),
  taxId: text("tax_id"), // CUIT/CUIL/DNI
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});

// === SALES ===
export const sales = pgTable("sales", {
  id: serial("id").primaryKey(),
  receiptNumber: text("receipt_number").unique(), // Autogenerated receipt #
  clientId: integer("client_id").references(() => clients.id),
  userId: text("user_id").references(() => users.id), // Who made the sale (Replit Auth ID is string)
  totalAmount: numeric("total_amount", { precision: 10, scale: 2 }).notNull(),
  paymentMethod: text("payment_method").notNull(), // cash, card, transfer, etc.
  status: text("status").default("completed"), // completed, cancelled, pending
  createdAt: timestamp("created_at").defaultNow(),
});

export const saleItems = pgTable("sale_items", {
  id: serial("id").primaryKey(),
  saleId: integer("sale_id").notNull().references(() => sales.id),
  productId: integer("product_id").notNull().references(() => products.id),
  quantity: integer("quantity").notNull(),
  unitPrice: numeric("unit_price", { precision: 10, scale: 2 }).notNull(), // Price at moment of sale
  subtotal: numeric("subtotal", { precision: 10, scale: 2 }).notNull(),
});

// === RELATIONS ===
export const productRelations = relations(products, ({ one }) => ({
  category: one(categories, {
    fields: [products.categoryId],
    references: [categories.id],
  }),
}));

export const saleRelations = relations(sales, ({ one, many }) => ({
  client: one(clients, {
    fields: [sales.clientId],
    references: [clients.id],
  }),
  items: many(saleItems),
}));

export const saleItemRelations = relations(saleItems, ({ one }) => ({
  sale: one(sales, {
    fields: [saleItems.saleId],
    references: [sales.id],
  }),
  product: one(products, {
    fields: [saleItems.productId],
    references: [products.id],
  }),
}));

// === ZOD SCHEMAS ===
export const insertCategorySchema = createInsertSchema(categories).omit({ id: true });
export const insertProductSchema = createInsertSchema(products).omit({ id: true });
export const insertClientSchema = createInsertSchema(clients).omit({ id: true, createdAt: true });
export const insertSaleSchema = createInsertSchema(sales).omit({ id: true, receiptNumber: true, userId: true, createdAt: true });
export const insertSaleItemSchema = createInsertSchema(saleItems).omit({ id: true, saleId: true });

// === API TYPES ===
export type Product = typeof products.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type Sale = typeof sales.$inferSelect;
export type SaleItem = typeof saleItems.$inferSelect;

export type InsertProduct = z.infer<typeof insertProductSchema>;
export type InsertClient = z.infer<typeof insertClientSchema>;

// Custom Types for Frontend
export type ProductWithCategory = Product & { category: Category | null };

export type CreateSaleRequest = {
  clientId?: number;
  paymentMethod: string;
  items: {
    productId: number;
    quantity: number;
    unitPrice: number; // Frontend sends price, backend verifies/adjusts if needed but good for flexibility
  }[];
};

export type SaleWithDetails = Sale & {
  client: Client | null;
  items: (SaleItem & { product: Product })[];
};

export type DashboardStats = {
  totalSalesToday: number;
  revenueToday: number;
  lowStockCount: number;
  totalProducts: number;
  recentSales: SaleWithDetails[];
};
