import { pgTable, text, serial, integer, boolean, timestamp, numeric, jsonb } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { users } from "./models/auth";

// Export all auth models (users and sessions)
export * from "./models/auth";

// === PRODUCTS ===
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
});

export const products = pgTable("products", {
  id: serial("id").primaryKey(),
  sku: text("sku").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  categoryId: integer("category_id").references(() => categories.id),
  price: numeric("price", { precision: 10, scale: 2 }).notNull(),
  costPrice: numeric("cost_price", { precision: 10, scale: 2 }),
  stockQuantity: integer("stock_quantity").notNull().default(0),
  minStockLevel: integer("min_stock_level").default(5),
  imageUrl: text("image_url"),
  isActive: boolean("is_active").default(true),
});

// === CLIENTS ===
export const clients = pgTable("clients", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  businessName: text("business_name"), // Razón social
  email: text("email"),
  phone: text("phone"),
  whatsapp: text("whatsapp"),
  address: text("address"),
  city: text("city"),
  province: text("province"),
  postalCode: text("postal_code"),
  taxId: text("tax_id"), // CUIT/CUIL/DNI
  taxCondition: text("tax_condition").default("consumidor_final"), // consumidor_final, responsable_inscripto, monotributista, exento
  discountPercent: numeric("discount_percent", { precision: 5, scale: 2 }).default("0"),
  creditLimit: numeric("credit_limit", { precision: 12, scale: 2 }).default("0"),
  notes: text("notes"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// === AUTHORIZED CONTACTS (Personas autorizadas por cliente) ===
export const clientAuthorizedContacts = pgTable("client_authorized_contacts", {
  id: serial("id").primaryKey(),
  clientId: integer("client_id").notNull().references(() => clients.id),
  name: text("name").notNull(),
  dni: text("dni"),
  phone: text("phone"),
  email: text("email"),
  position: text("position"), // Cargo: encargado, dueño, empleado
  notes: text("notes"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// === CURRENT ACCOUNT (Cuenta corriente) ===
export const clientAccountMovements = pgTable("client_account_movements", {
  id: serial("id").primaryKey(),
  clientId: integer("client_id").notNull().references(() => clients.id),
  type: text("type").notNull(), // debit (debe), credit (haber)
  amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
  balance: numeric("balance", { precision: 12, scale: 2 }).notNull(), // Running balance after this movement
  concept: text("concept").notNull(), // invoice, payment, delivery_note, adjustment, etc.
  referenceType: text("reference_type"), // sale, delivery_note, pre_invoice, payment
  referenceId: integer("reference_id"), // ID of related document
  documentNumber: text("document_number"), // Número de comprobante
  notes: text("notes"),
  userId: text("user_id").references(() => users.id),
  createdAt: timestamp("created_at").defaultNow(),
});

// === SALES ===
export const sales = pgTable("sales", {
  id: serial("id").primaryKey(),
  receiptNumber: text("receipt_number").unique(), // Autogenerated receipt #
  clientId: integer("client_id").references(() => clients.id),
  userId: text("user_id").references(() => users.id), // Who made the sale (Replit Auth ID is string)
  totalAmount: numeric("total_amount", { precision: 10, scale: 2 }).notNull(),
  paymentMethod: text("payment_method").notNull(), // cash, card, transfer, etc.
  status: text("status").default("completed"), // completed, cancelled, pending
  createdAt: timestamp("created_at").defaultNow(),
});

export const saleItems = pgTable("sale_items", {
  id: serial("id").primaryKey(),
  saleId: integer("sale_id").notNull().references(() => sales.id),
  productId: integer("product_id").notNull().references(() => products.id),
  quantity: integer("quantity").notNull(),
  unitPrice: numeric("unit_price", { precision: 10, scale: 2 }).notNull(), // Price at moment of sale
  subtotal: numeric("subtotal", { precision: 10, scale: 2 }).notNull(),
});

// === RELATIONS ===
export const productRelations = relations(products, ({ one }) => ({
  category: one(categories, {
    fields: [products.categoryId],
    references: [categories.id],
  }),
}));

export const saleRelations = relations(sales, ({ one, many }) => ({
  client: one(clients, {
    fields: [sales.clientId],
    references: [clients.id],
  }),
  items: many(saleItems),
}));

export const saleItemRelations = relations(saleItems, ({ one }) => ({
  sale: one(sales, {
    fields: [saleItems.saleId],
    references: [sales.id],
  }),
  product: one(products, {
    fields: [saleItems.productId],
    references: [products.id],
  }),
}));

// === DELIVERY NOTES (REMITOS) ===
export const deliveryNotes = pgTable("delivery_notes", {
  id: serial("id").primaryKey(),
  noteNumber: text("note_number").unique().notNull(), // R-0001, R-0002...
  clientId: integer("client_id").references(() => clients.id).notNull(),
  userId: text("user_id").references(() => users.id),
  status: text("status").default("pending"), // pending, invoiced, cancelled
  notes: text("notes"),
  deliveryDate: timestamp("delivery_date").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const deliveryNoteItems = pgTable("delivery_note_items", {
  id: serial("id").primaryKey(),
  deliveryNoteId: integer("delivery_note_id").notNull().references(() => deliveryNotes.id),
  productId: integer("product_id").notNull().references(() => products.id),
  quantity: integer("quantity").notNull(),
  unitPrice: numeric("unit_price", { precision: 10, scale: 2 }).notNull(),
  subtotal: numeric("subtotal", { precision: 10, scale: 2 }).notNull(),
});

// === PRE-INVOICES (PRE-FACTURAS) ===
export const preInvoices = pgTable("pre_invoices", {
  id: serial("id").primaryKey(),
  preInvoiceNumber: text("pre_invoice_number").unique().notNull(), // PF-0001, PF-0002...
  clientId: integer("client_id").references(() => clients.id).notNull(),
  userId: text("user_id").references(() => users.id),
  status: text("status").default("pending_review"), // pending_review, approved, rejected, invoiced
  totalAmount: numeric("total_amount", { precision: 10, scale: 2 }).notNull(),
  adminNotes: text("admin_notes"), // Notas de administración
  reviewedAt: timestamp("reviewed_at"),
  reviewedBy: text("reviewed_by"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Link table: which delivery notes are included in each pre-invoice
export const preInvoiceDeliveryNotes = pgTable("pre_invoice_delivery_notes", {
  id: serial("id").primaryKey(),
  preInvoiceId: integer("pre_invoice_id").notNull().references(() => preInvoices.id),
  deliveryNoteId: integer("delivery_note_id").notNull().references(() => deliveryNotes.id),
});

// === DELIVERY NOTE RELATIONS ===
export const deliveryNoteRelations = relations(deliveryNotes, ({ one, many }) => ({
  client: one(clients, {
    fields: [deliveryNotes.clientId],
    references: [clients.id],
  }),
  items: many(deliveryNoteItems),
}));

export const deliveryNoteItemRelations = relations(deliveryNoteItems, ({ one }) => ({
  deliveryNote: one(deliveryNotes, {
    fields: [deliveryNoteItems.deliveryNoteId],
    references: [deliveryNotes.id],
  }),
  product: one(products, {
    fields: [deliveryNoteItems.productId],
    references: [products.id],
  }),
}));

export const preInvoiceRelations = relations(preInvoices, ({ one, many }) => ({
  client: one(clients, {
    fields: [preInvoices.clientId],
    references: [clients.id],
  }),
  deliveryNotes: many(preInvoiceDeliveryNotes),
}));

export const preInvoiceDeliveryNoteRelations = relations(preInvoiceDeliveryNotes, ({ one }) => ({
  preInvoice: one(preInvoices, {
    fields: [preInvoiceDeliveryNotes.preInvoiceId],
    references: [preInvoices.id],
  }),
  deliveryNote: one(deliveryNotes, {
    fields: [preInvoiceDeliveryNotes.deliveryNoteId],
    references: [deliveryNotes.id],
  }),
}));

// === CLIENT RELATIONS ===
export const clientRelations = relations(clients, ({ many }) => ({
  authorizedContacts: many(clientAuthorizedContacts),
  accountMovements: many(clientAccountMovements),
  sales: many(sales),
  deliveryNotes: many(deliveryNotes),
}));

export const clientAuthorizedContactRelations = relations(clientAuthorizedContacts, ({ one }) => ({
  client: one(clients, {
    fields: [clientAuthorizedContacts.clientId],
    references: [clients.id],
  }),
}));

export const clientAccountMovementRelations = relations(clientAccountMovements, ({ one }) => ({
  client: one(clients, {
    fields: [clientAccountMovements.clientId],
    references: [clients.id],
  }),
}));

// === ZOD SCHEMAS ===
export const insertCategorySchema = createInsertSchema(categories).omit({ id: true });
export const insertProductSchema = createInsertSchema(products).omit({ id: true });
export const insertClientSchema = createInsertSchema(clients).omit({ id: true, createdAt: true, updatedAt: true });
export const insertSaleSchema = createInsertSchema(sales).omit({ id: true, receiptNumber: true, userId: true, createdAt: true });
export const insertSaleItemSchema = createInsertSchema(saleItems).omit({ id: true, saleId: true });
export const insertDeliveryNoteSchema = createInsertSchema(deliveryNotes).omit({ id: true, noteNumber: true, userId: true, createdAt: true });
export const insertDeliveryNoteItemSchema = createInsertSchema(deliveryNoteItems).omit({ id: true, deliveryNoteId: true });
export const insertPreInvoiceSchema = createInsertSchema(preInvoices).omit({ id: true, preInvoiceNumber: true, userId: true, createdAt: true, reviewedAt: true, reviewedBy: true });
export const insertAuthorizedContactSchema = createInsertSchema(clientAuthorizedContacts).omit({ id: true, createdAt: true });
export const insertAccountMovementSchema = createInsertSchema(clientAccountMovements).omit({ id: true, createdAt: true });

// === API TYPES ===
export type Product = typeof products.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type Sale = typeof sales.$inferSelect;
export type SaleItem = typeof saleItems.$inferSelect;
export type DeliveryNote = typeof deliveryNotes.$inferSelect;
export type DeliveryNoteItem = typeof deliveryNoteItems.$inferSelect;
export type PreInvoice = typeof preInvoices.$inferSelect;
export type PreInvoiceDeliveryNote = typeof preInvoiceDeliveryNotes.$inferSelect;
export type ClientAuthorizedContact = typeof clientAuthorizedContacts.$inferSelect;
export type ClientAccountMovement = typeof clientAccountMovements.$inferSelect;

export type InsertProduct = z.infer<typeof insertProductSchema>;
export type InsertClient = z.infer<typeof insertClientSchema>;
export type InsertDeliveryNote = z.infer<typeof insertDeliveryNoteSchema>;
export type InsertDeliveryNoteItem = z.infer<typeof insertDeliveryNoteItemSchema>;
export type InsertAuthorizedContact = z.infer<typeof insertAuthorizedContactSchema>;
export type InsertAccountMovement = z.infer<typeof insertAccountMovementSchema>;

// Custom Types for Frontend
export type ProductWithCategory = Product & { category: Category | null };

export type CreateSaleRequest = {
  clientId?: number;
  paymentMethod: string;
  items: {
    productId: number;
    quantity: number;
    unitPrice: number; // Frontend sends price, backend verifies/adjusts if needed but good for flexibility
  }[];
};

export type SaleWithDetails = Sale & {
  client: Client | null;
  items: (SaleItem & { product: Product })[];
};

export type DashboardStats = {
  totalSalesToday: number;
  revenueToday: number;
  lowStockCount: number;
  totalProducts: number;
  recentSales: SaleWithDetails[];
};

// Delivery Notes Types
export type DeliveryNoteWithDetails = DeliveryNote & {
  client: Client;
  items: (DeliveryNoteItem & { product: Product })[];
};

export type CreateDeliveryNoteRequest = {
  clientId: number;
  notes?: string;
  deliveryDate?: string;
  items: {
    productId: number;
    quantity: number;
    unitPrice: number;
  }[];
};

// Pre-Invoice Types
export type PreInvoiceWithDetails = PreInvoice & {
  client: Client;
  deliveryNotes: DeliveryNoteWithDetails[];
};

export type CreatePreInvoiceRequest = {
  clientId: number;
  deliveryNoteIds: number[];
};

// Client with pending delivery notes for grouping
export type ClientWithPendingNotes = Client & {
  pendingDeliveryNotes: DeliveryNoteWithDetails[];
  totalPendingAmount: number;
};

// === ADVANCED CLIENT TYPES ===
export type ClientWithDetails = Client & {
  authorizedContacts: ClientAuthorizedContact[];
  currentBalance: number;
};

export type ClientAccountSummary = {
  clientId: number;
  clientName: string;
  totalDebit: number;
  totalCredit: number;
  currentBalance: number;
  movements: ClientAccountMovement[];
};

export type CreateAccountMovementRequest = {
  clientId: number;
  type: "debit" | "credit";
  amount: number;
  concept: string;
  referenceType?: string;
  referenceId?: number;
  documentNumber?: string;
  notes?: string;
};
